# Generated by Django 4.0.4 on 2023-02-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_activity_date_activity_name_activity_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='email',
        ),
        migrations.AddField(
            model_name='contactus',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
