# Generated by Django 4.0.4 on 2023-02-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_contactus_email_contactus_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('booking_link', models.URLField()),
                ('images', models.ManyToManyField(to='common.galleryimage')),
            ],
        ),
    ]
