# Generated by Django 4.0.4 on 2023-03-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_rename_mobile_contactus_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
