# Generated by Django 4.0.4 on 2023-03-25 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_facility_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.facility')),
            ],
        ),
    ]
