# Generated by Django 4.0.4 on 2023-03-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_facilitygalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslideritem',
            name='description',
            field=models.TextField(default='description'),
        ),
    ]
